name: buahtangan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  intl: 0.17.0
  google_nav_bar: 5.0.6
  get_storage: 2.0.3
  flutter_iconly: 1.0.2
  google_fonts: 3.0.1
  firebase_core: ^1.17.1
  firebase_auth: 3.3.19
  cloud_firestore: 3.1.17
  firebase_storage: 10.2.17
  # image_picker: 0.8.5+3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

