name: buahtangan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: 4.1.1
  cloud_firestore: 3.1.17
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  firebase_auth: 3.3.19
  firebase_core: ^1.17.1
  firebase_storage: 10.2.17
  flutter:
    sdk: flutter
  flutter_facebook_auth: 4.3.4+2
  flutter_iconly: 1.0.2
  flutter_rating_bar: ^4.0.1
  flutter_svg: 1.1.0
  get: 4.6.5
  get_storage: 2.0.3
  google_fonts: 3.0.1
  google_nav_bar: 5.0.6
  google_sign_in: 5.3.3
  image_picker: 0.8.5+3
  intl: 0.17.0
  lottie: 1.3.0
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  sizer: ^2.0.15
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/lottie/
  uses-material-design: true
