import 'package:flutter/material.dart';

var primaryColor = const Color(0xFF034A64);
var primaryVariantColor = const Color(0xFF013142);
var secondaryColor = const Color(0xFFED6F6A);
var secondaryVariantColor = const Color(0xFFE15655);
var tertiaryColor = const Color(0xFFA7D6EA);
var tertiaryVariantColor = const Color(0xFF61B9E9);
var backgroundColor = const Color(0xFFFAFAFA);
var surfaceColor = const Color(0xFFFFFFFF);
var errorColor = const Color(0xFFB00020);
var onPrimaryColor = const Color(0xFFFFFFFF);
var onSecondaryColor = const Color(0xFFFFFFFF);
var onTertiaryColor = const Color(0xFFFFFFFF);
var onBackgroundColor = const Color(0xFF1E293B);
var onSurfaceColor = const Color(0xFF334155);
var onErrorColor = const Color(0xFFFFFFFF);
var slate300 = const Color(0xFFCBD5E1);
var slate400 = const Color(0xFF94A3B8);
var slate500 = const Color(0xFF64748B);