// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSKNSqZDK5eqwk-Day6MgVM-yA-H0H4qo',
    appId: '1:954777707606:web:1fe84c705e9d9e5cc5c7f7',
    messagingSenderId: '954777707606',
    projectId: 'buahtangan-aa1b2',
    authDomain: 'buahtangan-aa1b2.firebaseapp.com',
    storageBucket: 'buahtangan-aa1b2.appspot.com',
    measurementId: 'G-1J1H0KNCEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhDcXg3NeoGRzSKZLjwhlVZSNzaTm3PkU',
    appId: '1:954777707606:android:d7c6dee3218588e3c5c7f7',
    messagingSenderId: '954777707606',
    projectId: 'buahtangan-aa1b2',
    storageBucket: 'buahtangan-aa1b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrv5dzmqJrJURhAfo2BqbhV13fbh4Kr2k',
    appId: '1:954777707606:ios:c52141cb230de2cac5c7f7',
    messagingSenderId: '954777707606',
    projectId: 'buahtangan-aa1b2',
    storageBucket: 'buahtangan-aa1b2.appspot.com',
    iosClientId: '954777707606-n0gmq2qb6u6fo794opu4uhtm1gt126c2.apps.googleusercontent.com',
    iosBundleId: 'com.rahdeva.buahtangan',
  );
}
